/*************************************************************************************************************
 * @name			Constants_Integrations
 * @author			Julian Hurtado <email@email.com>
 * @created			18 / 09 / 2025
 * @description		Constant values for Integrations
 *
 * Changes (version)
 * -----------------------------------------------------------------------------------------------------------
 * 				No.		Date			Author					Description
 * 				----	------------	--------------------	----------------------------------------------
 * @version		1.0		2025-09-18		Julian Hurtado			Created
 *
 **************************************************************************************************************/
public with sharing class Constants_Integrations {
}